function parseaFechasPRR(f){
  const partesFecha = f.split("/"); // Dividir la cadena en partes usando "/"
  const dia = parseInt(partesFecha[0], 10); // Convertir el mes a un número entero (base 10)
  const mes = parseInt(partesFecha[1], 10); // Convertir el día a un número entero (base 10)
  const anyo = parseInt(partesFecha[2], 10);

  const fecha = new Date(anyo, mes - 1, dia); // Nota: Restamos 1 del mes, ya que los meses en JavaScript van de 0 a 11

  return fecha;
}

let array = [
  {
    "team": "ARG",
    "plabel": "Lock",
    "age": 27,
    "height": 198,
    "weight": 112,
    "bplace": "Argentina",
    "bdate": parseaFechasPRR("05/12/1991"),
    "last": "Alemanno",
    "first": "Matias Ignacio",
    "caps": 57
  },
  {
    "team": "ARG",
    "plabel": "Full Back",
    "age": 24,
    "height": 191,
    "weight": 91,
    "bplace": "Argentina",
    "bdate": parseaFechasPRR("16/01/1995"),
    "last": "Boffelli",
    "first": "Emiliano",
    "caps": 25
  },
  {
    "team": "ARG",
    "plabel": "Back Row",
    "age": 26,
    "height": 187,
    "weight": 109,
    "bplace": "Argentina",
    "bdate": parseaFechasPRR("03/09/1993"),
    "last": "Bruni Pleininger",
    "first": "Rodrigo",
    "caps": 3
  },
  {
    "team": "ARG",
    "plabel": "Full Back",
    "age": 21,
    "height": 181,
    "weight": 82,
    "bplace": "Argentina",
    "bdate": parseaFechasPRR("30/03/1998"),
    "last": "Carreras",
    "first": "Santiago",
    "caps": 1
  },
  {
    "team": "ARG",
    "plabel": "Hooker",
    "age": 34,
    "height": 182,
    "weight": 106,
    "bplace": "Argentina",
    "bdate": parseaFechasPRR("15/03/1985"),
    "last": "Creevy",
    "first": "Agustín",
    "caps": 85
  },
  {
    "team": "ARG",
    "plabel": "Scrum Half",
    "age": 30,
    "height": 175,
    "weight": 79,
    "bplace": "Argentina",
    "bdate": parseaFechasPRR("12/06/1989"),
    "last": "Cubelli",
    "first": "Tomas Maria",
    "caps": 72
  },
  {
    "team": "ARG",
    "plabel": "Centre",
    "age": 28,
    "height": 183,
    "weight": 93,
    "bplace": "Argentina",
    "bdate": parseaFechasPRR("24/02/1991"),
    "last": "De La Fuente",
    "first": "Jeronimo",
    "caps": 50
  },
  {
    "team": "ARG",
    "plabel": "Wing",
    "age": 22,
    "height": 178,
    "weight": 80,
    "bplace": "Argentina",
    "bdate": parseaFechasPRR("22/04/1997"),
    "last": "Delguy",
    "first": "Bautista",
    "caps": 11
  },
  {
    "team": "CAN",
    "plabel": "Prop",
    "age": 25,
    "height": 185,
    "weight": 124,
    "bplace": "Canada",
    "bdate": parseaFechasPRR("24/05/1994"),
    "last": "Duru-Sears",
    "first": "Djustice Uchechukwe Quisbert Se",
    "caps": 49
  },
  {
    "team": "CAN",
    "plabel": "Wing",
    "age": 28,
    "height": 178,
    "weight": 93,
    "bplace": "Canada",
    "bdate": parseaFechasPRR("21/08/1991"),
    "last": "Hassler",
    "first": "Jeffrey",
    "caps": 24
  },
  {
    "team": "CAN",
    "plabel": "Centre",
    "age": 33,
    "height": 191,
    "weight": 102,
    "bplace": "Canada",
    "bdate": parseaFechasPRR("30/12/1985"),
    "last": "Hearn",
    "first": "Ciaran Patrick",
    "caps": 70
  },
  {
    "team": "CAN",
    "plabel": "Back Row",
    "age": 26,
    "height": 186,
    "weight": 94,
    "bplace": "Canada",
    "bdate": parseaFechasPRR("09/02/1993"),
    "last": "Heaton",
    "first": "Matthew Josef",
    "caps": 25
  },
  {
    "team": "CAN",
    "plabel": "Hooker",
    "age": 26,
    "height": 175,
    "weight": 104,
    "bplace": "Canada",
    "bdate": parseaFechasPRR("05/09/1993"),
    "last": "Howard",
    "first": "Eric Gerald",
    "caps": 23
  },
  {
    "team": "CAN",
    "plabel": "Prop",
    "age": 27,
    "height": 180,
    "weight": 118,
    "bplace": "Canada",
    "bdate": parseaFechasPRR("24/02/1992"),
    "last": "Ilnicki",
    "first": "Jake Henry",
    "caps": 36
  },
  {
    "team": "CAN",
    "plabel": "Prop",
    "age": 22,
    "height": 186,
    "weight": 122,
    "bplace": "Canada",
    "bdate": parseaFechasPRR("07/05/1997"),
    "last": "Keith",
    "first": "Cole Vance",
    "caps": 14
  },
  {
    "team": "CAN",
    "plabel": "Lock",
    "age": 23,
    "height": 199,
    "weight": 118,
    "bplace": "Canada",
    "bdate": parseaFechasPRR("09/07/1996"),
    "last": "Keys",
    "first": "Conor Harris",
    "caps": 16
  },
  {
    "team": "CAN",
    "plabel": "Centre",
    "age": 23,
    "height": 183,
    "weight": 97,
    "bplace": "Canada",
    "bdate": parseaFechasPRR("24/11/1995"),
    "last": "Lesage",
    "first": "Benjamin Boselli",
    "caps": 15
  },
  {
    "team": "CAN",
    "plabel": "Scrum Half",
    "age": 33,
    "height": 170,
    "weight": 80,
    "bplace": "Canada",
    "bdate": parseaFechasPRR("18/09/1985"),
    "last": "Mack",
    "first": "Philip Paul Robert",
    "caps": 57
  },
  {
    "team": "CAN",
    "plabel": "Scrum Half",
    "age": 30,
    "height": 175,
    "weight": 90,
    "bplace": "Scotland",
    "bdate": parseaFechasPRR("28/02/1989"),
    "last": "Mackenzie",
    "first": "Jamie Lee",
    "caps": 19
  },
  {
    "team": "CAN",
    "plabel": "Fly Half",
    "age": 31,
    "height": 178,
    "weight": 82,
    "bplace": "Hong Kong",
    "bdate": parseaFechasPRR("12/05/1988"),
    "last": "McRorie",
    "first": "Gordon Alexander",
    "caps": 43
  },
  {
    "team": "CAN",
    "plabel": "Fly Half",
    "age": 26,
    "height": 180,
    "weight": 87,
    "bplace": "Ireland",
    "bdate": parseaFechasPRR("05/10/1992"),
    "last": "Nelson",
    "first": "Peter",
    "caps": 4
  },
  {
    "team": "CAN",
    "plabel": "Fly Half",
    "age": 26,
    "height": 178,
    "weight": 89,
    "bplace": "Ireland",
    "bdate": parseaFechasPRR("12/03/1993"),
    "last": "O'Leary",
    "first": "Shane Patrick",
    "caps": 13
  },
  {
    "team": "CAN",
    "plabel": "Lock",
    "age": 28,
    "height": 197,
    "weight": 115,
    "bplace": "Canada",
    "bdate": parseaFechasPRR("21/02/1991"),
    "last": "Olmstead",
    "first": "Evan Dennis",
    "caps": 31
  },
  {
    "team": "CAN",
    "plabel": "Fly Half",
    "age": 27,
    "height": 185,
    "weight": 95,
    "bplace": "Canada",
    "bdate": parseaFechasPRR("01/11/1991"),
    "last": "Parfrey",
    "first": "Patrick Brian",
    "caps": 30
  },
  {
    "team": "CAN",
    "plabel": "Wing",
    "age": 26,
    "height": 183,
    "weight": 93,
    "bplace": "Canada",
    "bdate": parseaFechasPRR("06/10/1992"),
    "last": "Paris",
    "first": "Taylor Flavio",
    "caps": 27
  },
  {
    "team": "CAN",
    "plabel": "Hooker",
    "age": 32,
    "height": 183,
    "weight": 108,
    "bplace": "Canada",
    "bdate": parseaFechasPRR("21/05/1987"),
    "last": "Piffero",
    "first": "Benoit Serge Fernand",
    "caps": 24
  },
  {
    "team": "CAN",
    "plabel": "Hooker",
    "age": 23,
    "height": 183,
    "weight": 114,
    "bplace": "Canada",
    "bdate": parseaFechasPRR("29/08/1996"),
    "last": "Quattrin",
    "first": "Andrew Joseph",
    "caps": 3
  },
  {
    "team": "CAN",
    "plabel": "Back Row",
    "age": 24,
    "height": 188,
    "weight": 105,
    "bplace": "Canada",
    "bdate": parseaFechasPRR("02/08/1995"),
    "last": "Rumball",
    "first": "Lucas James",
    "caps": 32
  },
  {
    "team": "CAN",
    "plabel": "Lock",
    "age": 30,
    "height": 193,
    "weight": 113,
    "bplace": "Canada",
    "bdate": parseaFechasPRR("20/12/1988"),
    "last": "Sheppard",
    "first": "Michael Allen",
    "caps": 8
  },
  {
    "team": "CAN",
    "plabel": "Prop",
    "age": 23,
    "height": 188,
    "weight": 127,
    "bplace": "Canada",
    "bdate": parseaFechasPRR("04/07/1996"),
    "last": "Tierney",
    "first": "Matthew Martin Joseph",
    "caps": 20
  },
  {
    "team": "CAN",
    "plabel": "Centre",
    "age": 29,
    "height": 190,
    "weight": 102,
    "bplace": "Canada",
    "bdate": parseaFechasPRR("05/12/1989"),
    "last": "Trainor",
    "first": "Conor Adam",
    "caps": 34
  },
  {
    "team": "CAN",
    "plabel": "Wing",
    "age": 33,
    "height": 183,
    "weight": 98,
    "bplace": "South Africa",
    "bdate": parseaFechasPRR("28/04/1986"),
    "last": "Van Der Merwe",
    "first": "Daniel Tailliferre Hauman",
    "caps": 58
  },
  {
    "team": "CAN",
    "plabel": "Lock",
    "age": 25,
    "height": 196,
    "weight": 112,
    "bplace": "Canada",
    "bdate": parseaFechasPRR("04/04/1994"),
    "last": "Larsen",
    "first": "Joshua Shorewood",
    "caps": 12
  },
  {
    "team": "ENG",
    "plabel": "Wing",
    "age": 21,
    "height": 193,
    "weight": 122,
    "bplace": "Fiji",
    "bdate": parseaFechasPRR("15/11/1997"),
    "last": "Cokanasiga",
    "first": "Ratu Josateki Tuivanuavou W",
    "caps": 8
  },
  {
    "team": "ENG",
    "plabel": "Prop",
    "age": 32,
    "height": 191,
    "weight": 118,
    "bplace": "England",
    "bdate": parseaFechasPRR("09/05/1987"),
    "last": "Cole",
    "first": "Daniel Richard",
    "caps": 89
  },
  {
    "team": "ENG",
    "plabel": "Hooker",
    "age": 26,
    "height": 184,
    "weight": 109,
    "bplace": "England",
    "bdate": parseaFechasPRR("20/06/1993"),
    "last": "Cowan-Dickie",
    "first": "Luke Anthony",
    "caps": 15
  },
  {
    "team": "ENG",
    "plabel": "Back Row",
    "age": 21,
    "height": 185,
    "weight": 106,
    "bplace": "England",
    "bdate": parseaFechasPRR("15/06/1998"),
    "last": "Curry",
    "first": "Thomas Anthony",
    "caps": 13
  },
  {
    "team": "ENG",
    "plabel": "Full Back",
    "age": 26,
    "height": 184,
    "weight": 94,
    "bplace": "England",
    "bdate": parseaFechasPRR("08/10/1992"),
    "last": "Daly",
    "first": "Elliot Fitzgerald",
    "caps": 33
  },
  {
    "team": "ENG",
    "plabel": "Fly Half",
    "age": 27,
    "height": 188,
    "weight": 92,
    "bplace": "England",
    "bdate": parseaFechasPRR("24/09/1991"),
    "last": "Farrell",
    "first": "Owen Andrew",
    "caps": 73
  },
  {
    "team": "ENG",
    "plabel": "Fly Half",
    "age": 26,
    "height": 178,
    "weight": 84,
    "bplace": "England",
    "bdate": parseaFechasPRR("16/03/1993"),
    "last": "Ford",
    "first": "George Thomas",
    "caps": 59
  },
  {
    "team": "ENG",
    "plabel": "Centre",
    "age": 29,
    "height": 183,
    "weight": 91,
    "bplace": "England",
    "bdate": parseaFechasPRR("20/06/1990"),
    "last": "Francis",
    "first": "Piers George",
    "caps": 8
  },
  {
    "team": "ENG",
    "plabel": "Prop",
    "age": 24,
    "height": 187,
    "weight": 113,
    "bplace": "England",
    "bdate": parseaFechasPRR("16/02/1995"),
    "last": "Genge",
    "first": "Ellis",
    "caps": 12
  },
  {
    "team": "ENG",
    "plabel": "Hooker",
    "age": 28,
    "height": 183,
    "weight": 109,
    "bplace": "England",
    "bdate": parseaFechasPRR("20/10/1990"),
    "last": "George",
    "first": "Jamie Edward",
    "caps": 40
  },
  {
    "team": "ENG",
    "plabel": "Scrum Half",
    "age": 32,
    "height": 182,
    "weight": 89,
    "bplace": "New Zealand",
    "bdate": parseaFechasPRR("24/11/1986"),
    "last": "Heinz",
    "first": "William Alexander",
    "caps": 4
  },
  {
    "team": "ENG",
    "plabel": "Lock",
    "age": 24,
    "height": 195,
    "weight": 115,
    "bplace": "England",
    "bdate": parseaFechasPRR("28/10/1994"),
    "last": "Itoje",
    "first": "Oghenemaro Miles",
    "caps": 29
  },
  {
    "team": "ENG",
    "plabel": "Centre",
    "age": 28,
    "height": 183,
    "weight": 93,
    "bplace": "England",
    "bdate": parseaFechasPRR("21/05/1991"),
    "last": "Joseph",
    "first": "Jonathan Byron Alexander",
    "caps": 42
  },
  {
    "team": "ENG",
    "plabel": "Lock",
    "age": 29,
    "height": 198,
    "weight": 117,
    "bplace": "England",
    "bdate": parseaFechasPRR("22/02/1990"),
    "last": "Kruis",
    "first": "George Edward John",
    "caps": 35
  },
  {
    "team": "ENG",
    "plabel": "Lock",
    "age": 28,
    "height": 196,
    "weight": 125,
    "bplace": "England",
    "bdate": parseaFechasPRR("12/04/1991"),
    "last": "Launchbury",
    "first": "Joseph Oliver",
    "caps": 61
  },
  {
    "team": "ENG",
    "plabel": "Lock",
    "age": 30,
    "height": 200,
    "weight": 119,
    "bplace": "England",
    "bdate": parseaFechasPRR("23/02/1989"),
    "last": "Lawes",
    "first": "Courtney Lindford",
    "caps": 75
  },
  {
    "team": "ENG",
    "plabel": "Back Row",
    "age": 23,
    "height": 190,
    "weight": 110,
    "bplace": "England",
    "bdate": parseaFechasPRR("08/12/1995"),
    "last": "Ludlam",
    "first": "Lewis Wesley",
    "caps": 2
  },
  {
    "team": "ENG",
    "plabel": "Prop",
    "age": 29,
    "height": 183,
    "weight": 120,
    "bplace": "England",
    "bdate": parseaFechasPRR("07/07/1990"),
    "last": "Marler",
    "first": "Joseph William",
    "caps": 62
  },
  {
    "team": "ENG",
    "plabel": "Wing",
    "age": 29,
    "height": 188,
    "weight": 90,
    "bplace": "England",
    "bdate": parseaFechasPRR("01/04/1990"),
    "last": "May",
    "first": "Jonathon James",
    "caps": 47
  },
  {
    "team": "ENG",
    "plabel": "Wing",
    "age": 27,
    "height": 190,
    "weight": 93,
    "bplace": "England",
    "bdate": parseaFechasPRR("23/10/1991"),
    "last": "McConnochie",
    "first": "Ruaridh Lawson",
    "caps": 1
  },
  {
    "team": "ENG",
    "plabel": "Wing",
    "age": 26,
    "height": 180,
    "weight": 98,
    "bplace": "England",
    "bdate": parseaFechasPRR("11/04/1993"),
    "last": "Nowell",
    "first": "Jack Thomas",
    "caps": 33
  },
  {
    "team": "ENG",
    "plabel": "Prop",
    "age": 26,
    "height": 183,
    "weight": 116,
    "bplace": "England",
    "bdate": parseaFechasPRR("30/03/1993"),
    "last": "Sinckler",
    "first": "Kyle Norval Jonathan Sean",
    "caps": 25
  },
  {
    "team": "ENG",
    "plabel": "Hooker",
    "age": 23,
    "height": 180,
    "weight": 111,
    "bplace": "England",
    "bdate": parseaFechasPRR("14/05/1996"),
    "last": "Singleton",
    "first": "Jack Howard",
    "caps": 2
  },
  {
    "team": "ENG",
    "plabel": "Centre",
    "age": 26,
    "height": 188,
    "weight": 95,
    "bplace": "England",
    "bdate": parseaFechasPRR("19/03/1993"),
    "last": "Slade",
    "first": "Henry James Harvey",
    "caps": 22
  },
  {
    "team": "ENG",
    "plabel": "Centre",
    "age": 28,
    "height": 185,
    "weight": 112,
    "bplace": "Samoa",
    "bdate": parseaFechasPRR("18/05/1991"),
    "last": "Tuilagi",
    "first": "Etuale Manusamoa",
    "caps": 35
  },
  {
    "team": "ENG",
    "plabel": "Back Row",
    "age": 23,
    "height": 186,
    "weight": 106,
    "bplace": "Ohio, United States",
    "bdate": parseaFechasPRR("22/07/1996"),
    "last": "Underhill",
    "first": "Samuel Gregory",
    "caps": 10
  },
  {
    "team": "ENG",
    "plabel": "Back Row",
    "age": 26,
    "height": 188,
    "weight": 126,
    "bplace": "Australia",
    "bdate": parseaFechasPRR("03/11/1992"),
    "last": "Vunipola",
    "first": "Viliami Moe Lotu A T K M",
    "caps": 45
  },
  {
    "team": "ENG",
    "plabel": "Prop",
    "age": 28,
    "height": 180,
    "weight": 123,
    "bplace": "New Zealand",
    "bdate": parseaFechasPRR("14/01/1991"),
    "last": "Vunipola",
    "first": "Makovina Wanangarua I Whanga",
    "caps": 54
  },
  {
    "team": "ENG",
    "plabel": "Wing",
    "age": 25,
    "height": 188,
    "weight": 95,
    "bplace": "England",
    "bdate": parseaFechasPRR("26/02/1994"),
    "last": "Watson",
    "first": "Anthony Kenneth Chisom",
    "caps": 36
  },
  {
    "team": "ENG",
    "plabel": "Back Row",
    "age": 29,
    "height": 188,
    "weight": 110,
    "bplace": "England",
    "bdate": parseaFechasPRR("06/10/1989"),
    "last": "Wilson",
    "first": "Mark",
    "caps": 15
  },
  {
    "team": "ENG",
    "plabel": "Scrum Half",
    "age": 30,
    "height": 178,
    "weight": 89,
    "bplace": "England",
    "bdate": parseaFechasPRR("05/09/1989"),
    "last": "Youngs",
    "first": "Ben Ryder",
    "caps": 89
  },
  {
    "team": "FIJ",
    "plabel": "Prop",
    "age": 31,
    "height": 180,
    "weight": 130,
    "bplace": "Fiji",
    "bdate": parseaFechasPRR("10/03/1988"),
    "last": "Atalifo",
    "first": "Lee-Roy Eliki",
    "caps": 10
  },
  {
    "team": "FIJ",
    "plabel": "Lock",
    "age": 32,
    "height": 200,
    "weight": 120,
    "bplace": "Fiji",
    "bdate": parseaFechasPRR("12/08/1987"),
    "last": "Cavubati",
    "first": "Tevita Gucake Naqaqa",
    "caps": 26
  },
  {
    "team": "FIJ",
    "plabel": "Hooker",
    "age": 24,
    "height": 161,
    "weight": 112,
    "bplace": "Fiji",
    "bdate": parseaFechasPRR("21/01/1995"),
    "last": "Dolokoto",
    "first": "Mesulame Vuwai",
    "caps": 6
  },
  {
    "team": "FIJ",
    "plabel": "Wing",
    "age": 35,
    "height": 189,
    "weight": 99,
    "bplace": "Fiji",
    "bdate": parseaFechasPRR("05/04/1984"),
    "last": "Goneva",
    "first": "Vereniki",
    "caps": 57
  },
  {
    "team": "FIJ",
    "plabel": "Prop",
    "age": 29,
    "height": 185,
    "weight": 105,
    "bplace": "Fiji",
    "bdate": parseaFechasPRR("16/06/1990"),
    "last": "Kovekalou",
    "first": "Peni Ravai",
    "caps": 29
  },
  {
    "team": "FIJ",
    "plabel": "Back Row",
    "age": 28,
    "height": 190,
    "weight": 97,
    "bplace": "Fiji",
    "bdate": parseaFechasPRR("27/10/1990"),
    "last": "Kunatani",
    "first": "Semi",
    "caps": 10
  },
  {
    "team": "FIJ",
    "plabel": "Scrum Half",
    "age": 23,
    "height": 178,
    "weight": 79,
    "bplace": "Fiji",
    "bdate": parseaFechasPRR("18/04/1996"),
    "last": "Lomani",
    "first": "Frank",
    "caps": 11
  },
  {
    "team": "FIJ",
    "plabel": "Prop",
    "age": 34,
    "height": 182,
    "weight": 114,
    "bplace": "Australia",
    "bdate": parseaFechasPRR("19/12/1984"),
    "last": "Ma'afu",
    "first": "George David Campese",
    "caps": 57
  },
  {
    "team": "FIJ",
    "plabel": "Back Row",
    "age": 27,
    "height": 196,
    "weight": 103,
    "bplace": "Fiji",
    "bdate": parseaFechasPRR("22/10/1991"),
    "last": "Mata",
    "first": "Viliame Sevakadrau",
    "caps": 13
  },
  {
    "team": "FIJ",
    "plabel": "Fly Half",
    "age": 28,
    "height": 184,
    "weight": 93,
    "bplace": "England",
    "bdate": parseaFechasPRR("05/10/1990"),
    "last": "Matavesi",
    "first": "Joshua Lewis",
    "caps": 21
  },
  {
    "team": "FIJ",
    "plabel": "Hooker",
    "age": 27,
    "height": 182,
    "weight": 102,
    "bplace": "England",
    "bdate": parseaFechasPRR("13/01/1992"),
    "last": "Matavesi",
    "first": "Samuel Sireli",
    "caps": 8
  },
  {
    "team": "FIJ",
    "plabel": "Scrum Half",
    "age": 30,
    "height": 179,
    "weight": 85,
    "bplace": "Fiji",
    "bdate": parseaFechasPRR("08/03/1989"),
    "last": "Matawalu",
    "first": "Nikola Leka",
    "caps": 36
  },
  {
    "team": "FIJ",
    "plabel": "Prop",
    "age": 23,
    "height": 189,
    "weight": 116,
    "bplace": "Fiji",
    "bdate": parseaFechasPRR("02/06/1996"),
    "last": "Mawi",
    "first": "Eroni Cama Talemaisolomoni",
    "caps": 9
  },
  {
    "team": "FIJ",
    "plabel": "Full Back",
    "age": 30,
    "height": 184,
    "weight": 94,
    "bplace": "Fiji",
    "bdate": parseaFechasPRR("15/05/1989"),
    "last": "Murimurivalu",
    "first": "Kini",
    "caps": 26
  },
  {
    "team": "FIJ",
    "plabel": "Lock",
    "age": 31,
    "height": 198,
    "weight": 117,
    "bplace": "Fiji",
    "bdate": parseaFechasPRR("02/04/1988"),
    "last": "Nakarawa",
    "first": "Leone",
    "caps": 57
  },
  {
    "team": "FIJ",
    "plabel": "Wing",
    "age": 27,
    "height": 183,
    "weight": 98,
    "bplace": "Fiji",
    "bdate": parseaFechasPRR("08/04/1992"),
    "last": "Nakosi",
    "first": "Filipo",
    "caps": 1
  },
  {
    "team": "FIJ",
    "plabel": "Lock",
    "age": 33,
    "height": 198,
    "weight": 114,
    "bplace": "Fiji",
    "bdate": parseaFechasPRR("11/07/1986"),
    "last": "Ratuniyarawa",
    "first": "Apisalome",
    "caps": 30
  },
  {
    "team": "FIJ",
    "plabel": "Lock",
    "age": 24,
    "height": 198,
    "weight": 110,
    "bplace": "Fiji",
    "bdate": parseaFechasPRR("08/05/1995"),
    "last": "Ratuva",
    "first": "Tevita Kasikasi",
    "caps": 3
  },
  {
    "team": "FIJ",
    "plabel": "Prop",
    "age": 30,
    "height": 189,
    "weight": 111,
    "bplace": "Fiji",
    "bdate": parseaFechasPRR("06/04/1989"),
    "last": "Romumu",
    "first": "Ratu Manasa Saulo",
    "caps": 42
  },
  {
    "team": "FIJ",
    "plabel": "Back Row",
    "age": 26,
    "height": 183,
    "weight": 104,
    "bplace": "Fiji",
    "bdate": parseaFechasPRR("17/01/1993"),
    "last": "Senibitu",
    "first": "Peceli Yato",
    "caps": 17
  },
  {
    "team": "FIJ",
    "plabel": "Scrum Half",
    "age": 30,
    "height": 174,
    "weight": 70,
    "bplace": "Fiji",
    "bdate": parseaFechasPRR("15/06/1989"),
    "last": "Seniloli",
    "first": "Ratu Henry Wainiu",
    "caps": 26
  },
  {
    "team": "FIJ",
    "plabel": "Wing",
    "age": 25,
    "height": 171,
    "weight": 92,
    "bplace": "Fiji",
    "bdate": parseaFechasPRR("04/02/1994"),
    "last": "Tuisova",
    "first": "Josua",
    "caps": 9
  },
  {
    "team": "FIJ",
    "plabel": "Centre",
    "age": 28,
    "height": 191,
    "weight": 106,
    "bplace": "Fiji",
    "bdate": parseaFechasPRR("30/08/1991"),
    "last": "Vatubua",
    "first": "Jale Kaikadavu",
    "caps": 15
  },
  {
    "team": "FIJ",
    "plabel": "Fly Half",
    "age": 26,
    "height": 172,
    "weight": 82,
    "bplace": "Fiji",
    "bdate": parseaFechasPRR("02/11/1992"),
    "last": "Veitokani",
    "first": "Alivereti",
    "caps": 8
  },
  {
    "team": "FIJ",
    "plabel": "Centre",
    "age": 30,
    "height": 178,
    "weight": 98,
    "bplace": "Fiji",
    "bdate": parseaFechasPRR("14/03/1989"),
    "last": "Veivuke",
    "first": "Levani Botia",
    "caps": 14
  },
  {
    "team": "FIJ",
    "plabel": "Back Row",
    "age": 34,
    "height": 186,
    "weight": 101,
    "bplace": "Fiji",
    "bdate": parseaFechasPRR("06/07/1985"),
    "last": "Voka",
    "first": "Mosese",
    "caps": 8
  },
  {
    "team": "FIJ",
    "plabel": "Fly Half",
    "age": 28,
    "height": 191,
    "weight": 89,
    "bplace": "Australia",
    "bdate": parseaFechasPRR("13/01/1991"),
    "last": "Volavola",
    "first": "Ben Thomas Tuvula",
    "caps": 31
  },
  {
    "team": "GEO",
    "plabel": "Hooker",
    "age": 19,
    "height": 178,
    "weight": 107,
    "bplace": "Georgia",
    "bdate": parseaFechasPRR("25/06/2000"),
    "last": "Karkadze",
    "first": "Vano",
    "caps": 3
  },
  {
    "team": "GEO",
    "plabel": "Fly Half",
    "age": 31,
    "height": 180,
    "weight": 82,
    "bplace": "Georgia",
    "bdate": parseaFechasPRR("20/01/1988"),
    "last": "Khmaladze",
    "first": "Lasha",
    "caps": 74
  },
  {
    "team": "GEO",
    "plabel": "Centre",
    "age": 21,
    "height": 185,
    "weight": 96,
    "bplace": "Georgia",
    "bdate": parseaFechasPRR("11/11/1997"),
    "last": "Kveseladze",
    "first": "Giorgi",
    "caps": 18
  },
  {
    "team": "GEO",
    "plabel": "Scrum Half",
    "age": 22,
    "height": 175,
    "weight": 75,
    "bplace": "Georgia",
    "bdate": parseaFechasPRR("14/10/1996"),
    "last": "Lobzhanidze",
    "first": "Vasil",
    "caps": 44
  },
  {
    "team": "GEO",
    "plabel": "Back Row",
    "age": 27,
    "height": 195,
    "weight": 110,
    "bplace": "Georgia",
    "bdate": parseaFechasPRR("30/06/1992"),
    "last": "Lomidze",
    "first": "Lasha",
    "caps": 46
  },
  {
    "team": "GEO",
    "plabel": "Fly Half",
    "age": 33,
    "height": 185,
    "weight": 93,
    "bplace": "Georgia",
    "bdate": parseaFechasPRR("02/06/1986"),
    "last": "Malaguradze",
    "first": "Lasha",
    "caps": 92
  },
  {
    "team": "GEO",
    "plabel": "Hooker",
    "age": 28,
    "height": 180,
    "weight": 100,
    "bplace": "Georgia",
    "bdate": parseaFechasPRR("02/10/1990"),
    "last": "Mamukashvili",
    "first": "Shalva",
    "caps": 67
  },
  {
    "team": "GEO",
    "plabel": "Full Back",
    "age": 26,
    "height": 185,
    "weight": 79,
    "bplace": "Georgia",
    "bdate": parseaFechasPRR("27/01/1993"),
    "last": "Matiashvili",
    "first": "Ioseb",
    "caps": 18
  },
  {
    "team": "GEO",
    "plabel": "Centre",
    "age": 26,
    "height": 194,
    "weight": 115,
    "bplace": "Georgia",
    "bdate": parseaFechasPRR("17/03/1993"),
    "last": "Mchedlidze",
    "first": "Tamaz",
    "caps": 52
  },
  {
    "team": "GEO",
    "plabel": "Prop",
    "age": 23,
    "height": 179,
    "weight": 113,
    "bplace": "Georgia",
    "bdate": parseaFechasPRR("24/05/1996"),
    "last": "Melikidze",
    "first": "Giorgi",
    "caps": 13
  },
  {
    "team": "GEO",
    "plabel": "Lock",
    "age": 28,
    "height": 200,
    "weight": 130,
    "bplace": "Georgia",
    "bdate": parseaFechasPRR("01/07/1991"),
    "last": "Mikautadze",
    "first": "Konstantine",
    "caps": 59
  },
  {
    "team": "GEO",
    "plabel": "Wing",
    "age": 21,
    "height": 191,
    "weight": 99,
    "bplace": "Georgia",
    "bdate": parseaFechasPRR("27/10/1997"),
    "last": "Modebadze",
    "first": "Miriani",
    "caps": 10
  },
  {
    "team": "GEO",
    "plabel": "Prop",
    "age": 29,
    "height": 186,
    "weight": 118,
    "bplace": "Georgia",
    "bdate": parseaFechasPRR("25/05/1990"),
    "last": "Nariashvili",
    "first": "Mikheil",
    "caps": 56
  },
  {
    "team": "GEO",
    "plabel": "Lock",
    "age": 34,
    "height": 194,
    "weight": 111,
    "bplace": "Georgia",
    "bdate": parseaFechasPRR("26/09/1984"),
    "last": "Nemsadze",
    "first": "Giorgi",
    "caps": 91
  },
  {
    "team": "GEO",
    "plabel": "Back Row",
    "age": 20,
    "height": 192,
    "weight": 105,
    "bplace": "Georgia",
    "bdate": parseaFechasPRR("29/10/1998"),
    "last": "Saginadze",
    "first": "Beka",
    "caps": 5
  },
  {
    "team": "GEO",
    "plabel": "Centre",
    "age": 26,
    "height": 185,
    "weight": 96,
    "bplace": "Russian Federation",
    "bdate": parseaFechasPRR("17/05/1993"),
    "last": "Sharikadze",
    "first": "Merab",
    "caps": 63
  },
  {
    "team": "GEO",
    "plabel": "Lock",
    "age": 35,
    "height": 193,
    "weight": 107,
    "bplace": "Georgia",
    "bdate": parseaFechasPRR("24/01/1984"),
    "last": "Sutiashvili",
    "first": "Shalva",
    "caps": 76
  },
  {
    "team": "GEO",
    "plabel": "Back Row",
    "age": 28,
    "height": 180,
    "weight": 104,
    "bplace": "Georgia",
    "bdate": parseaFechasPRR("08/04/1991"),
    "last": "Tkhilaishvili",
    "first": "Giorgi",
    "caps": 51
  },
  {
    "team": "GEO",
    "plabel": "Wing",
    "age": 31,
    "height": 181,
    "weight": 94,
    "bplace": "Georgia",
    "bdate": parseaFechasPRR("02/11/1987"),
    "last": "Todua",
    "first": "Alexander",
    "caps": 78
  },
  {
    "team": "IRE",
    "plabel": "Centre",
    "age": 29,
    "height": 198,
    "weight": 99,
    "bplace": "New Zealand",
    "bdate": parseaFechasPRR("07/04/1990"),
    "last": "Aki",
    "first": "Fua Leiofi",
    "caps": 20
  },
  {
    "team": "IRE",
    "plabel": "Lock",
    "age": 27,
    "height": 198,
    "weight": 112,
    "bplace": "Ireland",
    "bdate": parseaFechasPRR("08/01/1992"),
    "last": "Beirne",
    "first": "Tadhg Gerard",
    "caps": 8
  },
  {
    "team": "IRE",
    "plabel": "Fly Half",
    "age": 23,
    "height": 184,
    "weight": 87,
    "bplace": "New Zealand",
    "bdate": parseaFechasPRR("01/11/1995"),
    "last": "Carbery",
    "first": "Joseph",
    "caps": 19
  },
  {
    "team": "IRE",
    "plabel": "Fly Half",
    "age": 27,
    "height": 183,
    "weight": 88,
    "bplace": "Ireland",
    "bdate": parseaFechasPRR("31/08/1992"),
    "last": "Carty",
    "first": "Jack",
    "caps": 7
  },
  {
    "team": "IRE",
    "plabel": "Back Row",
    "age": 27,
    "height": 191,
    "weight": 111,
    "bplace": "Ireland",
    "bdate": parseaFechasPRR("29/07/1992"),
    "last": "Conan",
    "first": "Jack Edward",
    "caps": 16
  },
  {
    "team": "IRE",
    "plabel": "Wing",
    "age": 28,
    "height": 180,
    "weight": 91,
    "bplace": "Ireland",
    "bdate": parseaFechasPRR("11/07/1991"),
    "last": "Conway",
    "first": "Andrew Joseph",
    "caps": 15
  },
  {
    "team": "IRE",
    "plabel": "Hooker",
    "age": 33,
    "height": 180,
    "weight": 102,
    "bplace": "Ireland",
    "bdate": parseaFechasPRR("06/05/1986"),
    "last": "Cronin",
    "first": "Sean Michael",
    "caps": 70
  },
  {
    "team": "IRE",
    "plabel": "Wing",
    "age": 31,
    "height": 178,
    "weight": 86,
    "bplace": "Ireland",
    "bdate": parseaFechasPRR("02/10/1987"),
    "last": "Earls",
    "first": "Keith Gerard",
    "caps": 78
  },
  {
    "team": "TON",
    "plabel": "Wing",
    "age": 32,
    "height": 187,
    "weight": 101,
    "bplace": "New Zealand",
    "bdate": parseaFechasPRR("05/07/1987"),
    "last": "Vuna",
    "first": "Kerry Cooper",
    "caps": 13
  },
  {
    "team": "URY",
    "plabel": "Scrum Half",
    "age": 23,
    "height": 174,
    "weight": 78,
    "bplace": "Uruguay",
    "bdate": parseaFechasPRR("02/09/1996"),
    "last": "Arata Perrone",
    "first": "Santiago",
    "caps": 29
  },
  {
    "team": "URY",
    "plabel": "Prop",
    "age": 25,
    "height": 190,
    "weight": 114,
    "bplace": "Uruguay",
    "bdate": parseaFechasPRR("19/08/1994"),
    "last": "Arbelo Garcia",
    "first": "Diego",
    "caps": 5
  },
  {
    "team": "URY",
    "plabel": "Back Row",
    "age": 21,
    "height": 177,
    "weight": 90,
    "bplace": "Uruguay",
    "bdate": parseaFechasPRR("09/09/1998"),
    "last": "Ardao",
    "first": "Manuel",
    "caps": 3
  },
  {
    "team": "URY",
    "plabel": "Fly Half",
    "age": 28,
    "height": 178,
    "weight": 80,
    "bplace": "Uruguay",
    "bdate": parseaFechasPRR("12/04/1991"),
    "last": "Berchesi Pisano",
    "first": "Felipe",
    "caps": 29
  },
  {
    "team": "URY",
    "plabel": "Centre",
    "age": 23,
    "height": 178,
    "weight": 83,
    "bplace": "Uruguay",
    "bdate": parseaFechasPRR("06/09/1996"),
    "last": "Cat Piccardo",
    "first": "Juan Manuel",
    "caps": 25
  },
  {
    "team": "URY",
    "plabel": "Back Row",
    "age": 21,
    "height": 184,
    "weight": 90,
    "bplace": "Uruguay",
    "bdate": parseaFechasPRR("28/02/1998"),
    "last": "Civetta Ponce De Leon",
    "first": "Santiago",
    "caps": 3
  },
  {
    "team": "URY",
    "plabel": "Centre",
    "age": 22,
    "height": 178,
    "weight": 90,
    "bplace": "Uruguay",
    "bdate": parseaFechasPRR("11/09/1997"),
    "last": "Della Corte Bertoni",
    "first": "Agustin",
    "caps": 5
  },
  {
    "team": "URY",
    "plabel": "Back Row",
    "age": 23,
    "height": 189,
    "weight": 100,
    "bplace": "Uruguay",
    "bdate": parseaFechasPRR("07/03/1996"),
    "last": "Diana Olaso",
    "first": "Manuel",
    "caps": 13
  },
  {
    "team": "URY",
    "plabel": "Lock",
    "age": 25,
    "height": 193,
    "weight": 103,
    "bplace": "Uruguay",
    "bdate": parseaFechasPRR("18/08/1994"),
    "last": "Dotti Uria",
    "first": "Ignacio Francisco",
    "caps": 34
  },
  {
    "team": "URY",
    "plabel": "Prop",
    "age": 27,
    "height": 173,
    "weight": 105,
    "bplace": "Uruguay",
    "bdate": parseaFechasPRR("09/10/1991"),
    "last": "Echeverria Rodriguez",
    "first": "Juan Antonio",
    "caps": 41
  },
  {
    "team": "URY",
    "plabel": "Full Back",
    "age": 23,
    "height": 178,
    "weight": 75,
    "bplace": "Uruguay",
    "bdate": parseaFechasPRR("23/06/1996"),
    "last": "Etcheverry Cavanna",
    "first": "Felipe",
    "caps": 2
  },
  {
    "team": "URY",
    "plabel": "Wing",
    "age": 28,
    "height": 174,
    "weight": 78,
    "bplace": "Uruguay",
    "bdate": parseaFechasPRR("19/05/1991"),
    "last": "Favaro Garcia",
    "first": "Federico",
    "caps": 25
  },
  {
    "team": "URY",
    "plabel": "Centre",
    "age": 26,
    "height": 177,
    "weight": 90,
    "bplace": "Uruguay",
    "bdate": parseaFechasPRR("03/07/1993"),
    "last": "Freitas Alleges",
    "first": "Solen Nicolas",
    "caps": 25
  },
  {
    "team": "URY",
    "plabel": "Back Row",
    "age": 30,
    "height": 175,
    "weight": 90,
    "bplace": "Uruguay",
    "bdate": parseaFechasPRR("01/05/1989"),
    "last": "Gaminara",
    "first": "Juan Manuel",
    "caps": 57
  },
  {
    "team": "URY",
    "plabel": "Prop",
    "age": 24,
    "height": 184,
    "weight": 107,
    "bplace": "Uruguay",
    "bdate": parseaFechasPRR("02/07/1995"),
    "last": "Gattas Clavell",
    "first": "Facundo Eduardo",
    "caps": 23
  },
  {
    "team": "URY",
    "plabel": "Centre",
    "age": 22,
    "height": 180,
    "weight": 84,
    "bplace": "Uruguay",
    "bdate": parseaFechasPRR("22/10/1996"),
    "last": "Inciarte",
    "first": "Tomas",
    "caps": 11
  },
  {
    "team": "URY",
    "plabel": "Prop",
    "age": 21,
    "height": 182,
    "weight": 102,
    "bplace": "Uruguay",
    "bdate": parseaFechasPRR("12/09/1998"),
    "last": "Jaunsolo Mezzetta",
    "first": "Joaquin",
    "caps": 0
  },
  {
    "team": "URY",
    "plabel": "Hooker",
    "age": 25,
    "height": 184,
    "weight": 105,
    "bplace": "Uruguay",
    "bdate": parseaFechasPRR("01/07/1994"),
    "last": "Kessler Lordon",
    "first": "German Eduardo",
    "caps": 39
  },
  {
    "team": "URY",
    "plabel": "Lock",
    "age": 27,
    "height": 188,
    "weight": 100,
    "bplace": "Uruguay",
    "bdate": parseaFechasPRR("05/10/1991"),
    "last": "Lamanna Miranda",
    "first": "Franco",
    "caps": 42
  },
  {
    "team": "URY",
    "plabel": "Lock",
    "age": 22,
    "height": 200,
    "weight": 110,
    "bplace": "Uruguay",
    "bdate": parseaFechasPRR("23/04/1997"),
    "last": "Leindekar Virginio",
    "first": "Manuel",
    "caps": 10
  },
  {
    "team": "URY",
    "plabel": "Wing",
    "age": 31,
    "height": 181,
    "weight": 98,
    "bplace": "Uruguay",
    "bdate": parseaFechasPRR("06/07/1988"),
    "last": "Leivas Ballestrino",
    "first": "Luis Leandro",
    "caps": 67
  },
  {
    "team": "URY",
    "plabel": "Lock",
    "age": 30,
    "height": 188,
    "weight": 105,
    "bplace": "Uruguay",
    "bdate": parseaFechasPRR("27/04/1989"),
    "last": "Magno",
    "first": "Diego Gianni",
    "caps": 80
  },
  {
    "team": "URY",
    "plabel": "Full Back",
    "age": 29,
    "height": 181,
    "weight": 80,
    "bplace": "Uruguay",
    "bdate": parseaFechasPRR("05/10/1989"),
    "last": "Mieres Valente",
    "first": "Gaston",
    "caps": 62
  },
  {
    "team": "URY",
    "plabel": "Back Row",
    "age": 31,
    "height": 186,
    "weight": 108,
    "bplace": "Uruguay",
    "bdate": parseaFechasPRR("07/01/1988"),
    "last": "Nieto Serra",
    "first": "Alejandro Martin",
    "caps": 59
  },
  {
    "team": "URY",
    "plabel": "Scrum Half",
    "age": 28,
    "height": 176,
    "weight": 86,
    "bplace": "Uruguay",
    "bdate": parseaFechasPRR("08/03/1991"),
    "last": "Ormaechea",
    "first": "Agustin Leon",
    "caps": 41
  },
  {
    "team": "URY",
    "plabel": "Back Row",
    "age": 30,
    "height": 184,
    "weight": 97,
    "bplace": "Uruguay",
    "bdate": parseaFechasPRR("28/01/1989"),
    "last": "Ormaechea",
    "first": "Juan Diego",
    "caps": 27
  },
  {
    "team": "URY",
    "plabel": "Hooker",
    "age": 22,
    "height": 180,
    "weight": 100,
    "bplace": "Uruguay",
    "bdate": parseaFechasPRR("06/02/1997"),
    "last": "Pujadas Leon",
    "first": "Guillermo",
    "caps": 7
  },
  {
    "team": "URY",
    "plabel": "Prop",
    "age": 32,
    "height": 185,
    "weight": 115,
    "bplace": "Uruguay",
    "bdate": parseaFechasPRR("05/03/1987"),
    "last": "Rombys Aguzzi",
    "first": "Juan Pedro",
    "caps": 29
  },
  {
    "team": "USA",
    "plabel": "Centre",
    "age": 29,
    "height": 188,
    "weight": 105,
    "bplace": "United States",
    "bdate": parseaFechasPRR("13/01/1990"),
    "last": "Iosefo",
    "first": "Martin Mulipa",
    "caps": 6
  },
  {
    "team": "USA",
    "plabel": "Prop",
    "age": 32,
    "height": 180,
    "weight": 118,
    "bplace": "United States",
    "bdate": parseaFechasPRR("28/09/1986"),
    "last": "Kilifi",
    "first": "Olive Onelani",
    "caps": 27
  },
  {
    "team": "USA",
    "plabel": "Back Row",
    "age": 28,
    "height": 185,
    "weight": 107,
    "bplace": "New Zealand",
    "bdate": parseaFechasPRR("31/07/1991"),
    "last": "Lamborn",
    "first": "Tony Andrew",
    "caps": 19
  },
  {
    "team": "USA",
    "plabel": "Prop",
    "age": 24,
    "height": 183,
    "weight": 113,
    "bplace": "United States",
    "bdate": parseaFechasPRR("11/02/1995"),
    "last": "Lamositele",
    "first": "Titi Edward",
    "caps": 28
  },
  {
    "team": "USA",
    "plabel": "Lock",
    "age": 28,
    "height": 198,
    "weight": 122,
    "bplace": "United States",
    "bdate": parseaFechasPRR("26/03/1991"),
    "last": "Landry",
    "first": "Benjamin Joseph",
    "caps": 22
  },
  {
    "team": "USA",
    "plabel": "Centre",
    "age": 29,
    "height": 180,
    "weight": 114,
    "bplace": "New Zealand",
    "bdate": parseaFechasPRR("18/06/1990"),
    "last": "Lasike",
    "first": "Paul Hiko",
    "caps": 16
  },
  {
    "team": "USA",
    "plabel": "Fly Half",
    "age": 29,
    "height": 185,
    "weight": 92,
    "bplace": "Ireland",
    "bdate": parseaFechasPRR("26/02/1990"),
    "last": "MacGinty",
    "first": "Alan Leon",
    "caps": 24
  },
  {
    "team": "USA",
    "plabel": "Prop",
    "age": 27,
    "height": 183,
    "weight": 86,
    "bplace": "England",
    "bdate": parseaFechasPRR("23/02/1992"),
    "last": "Magie",
    "first": "William Mac Gregor",
    "caps": 25
  },
  {
    "team": "USA",
    "plabel": "Prop",
    "age": 27,
    "height": 183,
    "weight": 125,
    "bplace": "Ireland",
    "bdate": parseaFechasPRR("16/11/1991"),
    "last": "Mullen",
    "first": "Paul",
    "caps": 14
  },
  {
    "team": "USA",
    "plabel": "Centre",
    "age": 30,
    "height": 191,
    "weight": 104,
    "bplace": "California, United States",
    "bdate": parseaFechasPRR("22/09/1988"),
    "last": "Palamo",
    "first": "Thretton Davis",
    "caps": 18
  },
  {
    "team": "USA",
    "plabel": "Lock",
    "age": 28,
    "height": 204,
    "weight": 123,
    "bplace": "Australia",
    "bdate": parseaFechasPRR("26/03/1991"),
    "last": "Peterson",
    "first": "Gregory Howard",
    "caps": 26
  },
  {
    "team": "USA",
    "plabel": "Back Row",
    "age": 25,
    "height": 193,
    "weight": 99,
    "bplace": "United States",
    "bdate": parseaFechasPRR("13/06/1994"),
    "last": "Pinkelman",
    "first": "Benjamin Joseph",
    "caps": 2
  },
  {
    "team": "USA",
    "plabel": "Back Row",
    "age": 29,
    "height": 188,
    "weight": 106,
    "bplace": "Ireland",
    "bdate": parseaFechasPRR("10/03/1990"),
    "last": "Quill",
    "first": "John Francis",
    "caps": 36
  },
  {
    "team": "USA",
    "plabel": "Wing",
    "age": 31,
    "height": 192,
    "weight": 95,
    "bplace": "California, United States",
    "bdate": parseaFechasPRR("29/02/1988"),
    "last": "Scully",
    "first": "Blaine Hansen",
    "caps": 50
  },
  {
    "team": "USA",
    "plabel": "Hooker",
    "age": 26,
    "height": 183,
    "weight": 124,
    "bplace": "American Samoa",
    "bdate": parseaFechasPRR("04/10/1992"),
    "last": "Taufetee",
    "first": "Joseph Soosemea",
    "caps": 23
  },
  {
    "team": "USA",
    "plabel": "Wing",
    "age": 26,
    "height": 175,
    "weight": 93,
    "bplace": "United States",
    "bdate": parseaFechasPRR("23/07/1993"),
    "last": "Teo",
    "first": "Michael Paseka",
    "caps": 24
  },
  {
    "team": "USA",
    "plabel": "Scrum Half",
    "age": 20,
    "height": 183,
    "weight": 88,
    "bplace": "South Africa",
    "bdate": parseaFechasPRR("09/10/1998"),
    "last": "de Hass",
    "first": "Ruben Pieter",
    "caps": 13
  },
  {
    "team": "WAL",
    "plabel": "Wing",
    "age": 24,
    "height": 186,
    "weight": 95,
    "bplace": "Wales",
    "bdate": parseaFechasPRR("21/04/1995"),
    "last": "Adams",
    "first": "Joshua Huw",
    "caps": 14
  },
  {
    "team": "WAL",
    "plabel": "Wing",
    "age": 24,
    "height": 185,
    "weight": 97,
    "bplace": "England",
    "bdate": parseaFechasPRR("24/09/1994"),
    "last": "Amos",
    "first": "Hallam Benjamen",
    "caps": 20
  },
  {
    "team": "WAL",
    "plabel": "Lock",
    "age": 28,
    "height": 198,
    "weight": 124,
    "bplace": "England",
    "bdate": parseaFechasPRR("21/06/1991"),
    "last": "Ball",
    "first": "Jake",
    "caps": 36
  },
  {
    "team": "WAL",
    "plabel": "Lock",
    "age": 23,
    "height": 203,
    "weight": 117,
    "bplace": "Wales",
    "bdate": parseaFechasPRR("07/01/1996"),
    "last": "Beard",
    "first": "Adam James",
    "caps": 16
  },
  {
    "team": "WAL",
    "plabel": "Centre",
    "age": 31,
    "height": 188,
    "weight": 101,
    "bplace": "New Zealand",
    "bdate": parseaFechasPRR("05/10/1987"),
    "last": "Parkes",
    "first": "Hadleigh William",
    "caps": 18
  },
  {
    "team": "WAL",
    "plabel": "Fly Half",
    "age": 26,
    "height": 191,
    "weight": 92,
    "bplace": "Wales",
    "bdate": parseaFechasPRR("17/05/1993"),
    "last": "Patchell",
    "first": "Mathew Rhys",
    "caps": 13
  },
  {
    "team": "WAL",
    "plabel": "Back Row",
    "age": 28,
    "height": 185,
    "weight": 105,
    "bplace": "Wales",
    "bdate": parseaFechasPRR("30/12/1990"),
    "last": "Rajai-Navidi",
    "first": "Joshua",
    "caps": 19
  },
  {
    "team": "WAL",
    "plabel": "Back Row",
    "age": 32,
    "height": 198,
    "weight": 107,
    "bplace": "England",
    "bdate": parseaFechasPRR("07/08/1987"),
    "last": "Shingler",
    "first": "Aaron Craig",
    "caps": 20
  },
  {
    "team": "WAL",
    "plabel": "Prop",
    "age": 25,
    "height": 183,
    "weight": 116,
    "bplace": "Wales",
    "bdate": parseaFechasPRR("07/04/1994"),
    "last": "Smith",
    "first": "Nicky Paul",
    "caps": 31
  },
  {
    "team": "WAL",
    "plabel": "Back Row",
    "age": 30,
    "height": 188,
    "weight": 102,
    "bplace": "Wales",
    "bdate": parseaFechasPRR("06/08/1989"),
    "last": "Tipuric",
    "first": "Justin Charles",
    "caps": 66
  },
  {
    "team": "WAL",
    "plabel": "Back Row",
    "age": 21,
    "height": 188,
    "weight": 106,
    "bplace": "Wales",
    "bdate": parseaFechasPRR("25/09/1997"),
    "last": "Wainwright",
    "first": "Aaron James",
    "caps": 12
  },
  {
    "team": "WAL",
    "plabel": "Centre",
    "age": 22,
    "height": 188,
    "weight": 100,
    "bplace": "Wales",
    "bdate": parseaFechasPRR("12/10/1996"),
    "last": "Watkin",
    "first": "Owen Paul",
    "caps": 16
  },
  {
    "team": "WAL",
    "plabel": "Full Back",
    "age": 28,
    "height": 185,
    "weight": 87,
    "bplace": "Wales",
    "bdate": parseaFechasPRR("09/04/1991"),
    "last": "Williams",
    "first": "Liam Brian",
    "caps": 58
  },
  {
    "team": "WAL",
    "plabel": "Scrum Half",
    "age": 24,
    "height": 178,
    "weight": 77,
    "bplace": "Wales",
    "bdate": parseaFechasPRR("01/01/1995"),
    "last": "Williams",
    "first": "Tomos Geraint",
    "caps": 9
  }
];

export default array;
